// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xUS0c0tEWmL052VllxThHUac2lZ8dKc',
    appId: '1:200159049475:web:2ef65c983e38a91e259b36',
    messagingSenderId: '200159049475',
    projectId: 'fir-auth-4c7d1',
    authDomain: 'fir-auth-4c7d1.firebaseapp.com',
    storageBucket: 'fir-auth-4c7d1.appspot.com',
    measurementId: 'G-082C54S9FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtHHTylEA7SMN59e92W6XoGZNtatGv-_g',
    appId: '1:200159049475:android:3410a087bab42b4b259b36',
    messagingSenderId: '200159049475',
    projectId: 'fir-auth-4c7d1',
    storageBucket: 'fir-auth-4c7d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIvWtsaq3-JwAesoqW7yLTgul76o7pvuw',
    appId: '1:200159049475:ios:1255a582d8269043259b36',
    messagingSenderId: '200159049475',
    projectId: 'fir-auth-4c7d1',
    storageBucket: 'fir-auth-4c7d1.appspot.com',
    androidClientId: '200159049475-uv0smgdna0skh1oi34o6401l8kuqierd.apps.googleusercontent.com',
    iosClientId: '200159049475-hm4upch325q4i4l2av3o71evgmjs2flh.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIvWtsaq3-JwAesoqW7yLTgul76o7pvuw',
    appId: '1:200159049475:ios:1255a582d8269043259b36',
    messagingSenderId: '200159049475',
    projectId: 'fir-auth-4c7d1',
    storageBucket: 'fir-auth-4c7d1.appspot.com',
    androidClientId: '200159049475-uv0smgdna0skh1oi34o6401l8kuqierd.apps.googleusercontent.com',
    iosClientId: '200159049475-hm4upch325q4i4l2av3o71evgmjs2flh.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseTutorial',
  );
}
